package com.app.pojo;
// Generated 10 Jan, 2018 5:06:10 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "tutesmessanger")
public class Student implements java.io.Serializable {

	private Integer id;
	private Division division;
	private Institute institute;
	private Login login;
	private Parent parent;
	private String fname;
	private String father;
	private String lname;
	private String contactno;
	private String email;
	private Set<ExamSubjectStudentCompositTable> examSubjectStudentCompositTables = new HashSet<ExamSubjectStudentCompositTable>(
			0);
	private Set<ExamSubjectStudentCompositTable> examSubjectStudentCompositTables_1 = new HashSet<ExamSubjectStudentCompositTable>(
			0);

	public Student() {
	}

	public Student(String father) {
		this.father = father;
	}

	public Student(Division division, Institute institute, Login login, Parent parent, String fname, String father,
			String lname, String contactno, String email,
			Set<ExamSubjectStudentCompositTable> examSubjectStudentCompositTables,
			Set<ExamSubjectStudentCompositTable> examSubjectStudentCompositTables_1) {
		this.division = division;
		this.institute = institute;
		this.login = login;
		this.parent = parent;
		this.fname = fname;
		this.father = father;
		this.lname = lname;
		this.contactno = contactno;
		this.email = email;
		this.examSubjectStudentCompositTables = examSubjectStudentCompositTables;
		this.examSubjectStudentCompositTables_1 = examSubjectStudentCompositTables_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "divid")
	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "instid")
	public Institute getInstitute() {
		return this.institute;
	}

	public void setInstitute(Institute institute) {
		this.institute = institute;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loginid")
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parentid")
	public Parent getParent() {
		return this.parent;
	}

	public void setParent(Parent parent) {
		this.parent = parent;
	}

	@Column(name = "fName")
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "father", nullable = false, length = 50)
	public String getFather() {
		return this.father;
	}

	public void setFather(String father) {
		this.father = father;
	}

	@Column(name = "lName")
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@Column(name = "contactno", length = 20)
	public String getContactno() {
		return this.contactno;
	}

	public void setContactno(String contactno) {
		this.contactno = contactno;
	}

	@Column(name = "email", length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<ExamSubjectStudentCompositTable> getExamSubjectStudentCompositTables() {
		return this.examSubjectStudentCompositTables;
	}

	public void setExamSubjectStudentCompositTables(
			Set<ExamSubjectStudentCompositTable> examSubjectStudentCompositTables) {
		this.examSubjectStudentCompositTables = examSubjectStudentCompositTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<ExamSubjectStudentCompositTable> getExamSubjectStudentCompositTables_1() {
		return this.examSubjectStudentCompositTables_1;
	}

	public void setExamSubjectStudentCompositTables_1(
			Set<ExamSubjectStudentCompositTable> examSubjectStudentCompositTables_1) {
		this.examSubjectStudentCompositTables_1 = examSubjectStudentCompositTables_1;
	}

}
