package com.app.pojo;
// Generated 21 Dec, 2017 11:23:34 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exam generated by hbm2java
 */
@Entity
@Table(name = "exam", catalog = "tutesmessanger")
public class Exam implements java.io.Serializable {

	private Integer id;
	private transient ExamMode examMode;
	private transient ExamType examType;
	private Integer outOf;
	private Integer passingMarks;
	private Byte regular;
	private Date date;
	private Integer durationInMin;
	private transient Set<ExamSubjectStudentCompositTable> examSubjectStudentCompositTables = new HashSet<ExamSubjectStudentCompositTable>(
			0);

	public Exam() {
	}

	public Exam(Date date) {
		this.date = date;
	}

	public Exam(ExamMode examMode, ExamType examType, Integer outOf, Integer passingMarks, Byte regular, Date date,
			Integer durationInMin, Set<ExamSubjectStudentCompositTable> examSubjectStudentCompositTables) {
		this.examMode = examMode;
		this.examType = examType;
		this.outOf = outOf;
		this.passingMarks = passingMarks;
		this.regular = regular;
		this.date = date;
		this.durationInMin = durationInMin;
		this.examSubjectStudentCompositTables = examSubjectStudentCompositTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exam_mode_id")
	public ExamMode getExamMode() {
		return this.examMode;
	}

	public void setExamMode(ExamMode examMode) {
		this.examMode = examMode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exam_type_id")
	public ExamType getExamType() {
		return this.examType;
	}

	public void setExamType(ExamType examType) {
		this.examType = examType;
	}

	@Column(name = "out_of")
	public Integer getOutOf() {
		return this.outOf;
	}

	public void setOutOf(Integer outOf) {
		this.outOf = outOf;
	}

	@Column(name = "passing_marks")
	public Integer getPassingMarks() {
		return this.passingMarks;
	}

	public void setPassingMarks(Integer passingMarks) {
		this.passingMarks = passingMarks;
	}

	@Column(name = "regular")
	public Byte getRegular() {
		return this.regular;
	}

	public void setRegular(Byte regular) {
		this.regular = regular;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "duration_in_min")
	public Integer getDurationInMin() {
		return this.durationInMin;
	}

	public void setDurationInMin(Integer durationInMin) {
		this.durationInMin = durationInMin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exam")
	public Set<ExamSubjectStudentCompositTable> getExamSubjectStudentCompositTables() {
		return this.examSubjectStudentCompositTables;
	}

	public void setExamSubjectStudentCompositTables(
			Set<ExamSubjectStudentCompositTable> examSubjectStudentCompositTables) {
		this.examSubjectStudentCompositTables = examSubjectStudentCompositTables;
	}

}
