package com.app.pojo;
// Generated 14 Nov, 2017 11:41:36 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Institute generated by hbm2java
 */
@Entity
@Table(name = "institute", catalog = "tutesmessanger", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Institute implements java.io.Serializable {

	private Integer id;
	private String name;
	private String address;
	private String contactno;
	private String email;
	private Date subscriptionTill;
	private Boolean subscritionEnable;
	private Boolean enable;
	private transient Set<Branch> branches = new HashSet<Branch>(0);
	private transient Set<Teacher> teachers = new HashSet<Teacher>(0);
	private transient Set<Student> students = new HashSet<Student>(0);
	private transient Set<Student> students_1 = new HashSet<Student>(0);
	private transient Set<Teacher> teachers_1 = new HashSet<Teacher>(0);
	private transient Set<Branch> branches_1 = new HashSet<Branch>(0);

	public Institute() {
	}

	public Institute(String name) {
		this.name = name;
	}

	public Institute(String name, String address, String contactno, String email, Date subscriptionTill,
			Boolean subscritionEnable, Boolean enable, Set<Branch> branches, Set<Teacher> teachers,
			Set<Student> students, Set<Student> students_1, Set<Teacher> teachers_1, Set<Branch> branches_1) {
		this.name = name;
		this.address = address;
		this.contactno = contactno;
		this.email = email;
		this.subscriptionTill = subscriptionTill;
		this.subscritionEnable = subscritionEnable;
		this.enable = enable;
		this.branches = branches;
		this.teachers = teachers;
		this.students = students;
		this.students_1 = students_1;
		this.teachers_1 = teachers_1;
		this.branches_1 = branches_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "contactno", length = 15)
	public String getContactno() {
		return this.contactno;
	}

	public void setContactno(String contactno) {
		this.contactno = contactno;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Subscription_till", length = 10)
	public Date getSubscriptionTill() {
		return this.subscriptionTill;
	}

	public void setSubscriptionTill(Date subscriptionTill) {
		this.subscriptionTill = subscriptionTill;
	}

	@Column(name = "Subscrition_enable")
	public Boolean getSubscritionEnable() {
		return this.subscritionEnable;
	}

	public void setSubscritionEnable(Boolean subscritionEnable) {
		this.subscritionEnable = subscritionEnable;
	}

	@Column(name = "enable")
	public Boolean getEnable() {
		return this.enable;
	}

	public void setEnable(Boolean enable) {
		this.enable = enable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institute")
	public Set<Branch> getBranches() {
		return this.branches;
	}

	public void setBranches(Set<Branch> branches) {
		this.branches = branches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institute")
	public Set<Teacher> getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Set<Teacher> teachers) {
		this.teachers = teachers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institute")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institute")
	public Set<Student> getStudents_1() {
		return this.students_1;
	}

	public void setStudents_1(Set<Student> students_1) {
		this.students_1 = students_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institute")
	public Set<Teacher> getTeachers_1() {
		return this.teachers_1;
	}

	public void setTeachers_1(Set<Teacher> teachers_1) {
		this.teachers_1 = teachers_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institute")
	public Set<Branch> getBranches_1() {
		return this.branches_1;
	}

	public void setBranches_1(Set<Branch> branches_1) {
		this.branches_1 = branches_1;
	}

}
