package com.app.pojo;
// Generated Jul 23, 2017 7:06:59 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permissions generated by hbm2java
 */
@Entity
@Table(name = "permissions", catalog = "tutesmessanger")
public class Permissions implements java.io.Serializable {

	private Integer id;
	private boolean mailStudent;
	private boolean msgStudent;
	private boolean mailParent;
	private boolean fillSchedule;
	private boolean setExam;
	private boolean updateResults;
	private boolean authoriseStudent;
	private boolean authoriseTeacher;
	private boolean msgTeacher;
	private boolean fillAttendance;
	private boolean msgParent;
	private boolean mailTeacher;
	private Set<Teacher> teachers = new HashSet<Teacher>(0);

	public Permissions() {
	}

	public Permissions(boolean mailStudent, boolean msgStudent, boolean mailParent, boolean fillSchedule,
			boolean setExam, boolean updateResults, boolean authoriseStudent, boolean authoriseTeacher,
			boolean msgTeacher, boolean fillAttendance, boolean msgParent, boolean mailTeacher) {
		this.mailStudent = mailStudent;
		this.msgStudent = msgStudent;
		this.mailParent = mailParent;
		this.fillSchedule = fillSchedule;
		this.setExam = setExam;
		this.updateResults = updateResults;
		this.authoriseStudent = authoriseStudent;
		this.authoriseTeacher = authoriseTeacher;
		this.msgTeacher = msgTeacher;
		this.fillAttendance = fillAttendance;
		this.msgParent = msgParent;
		this.mailTeacher = mailTeacher;
	}

	public Permissions(boolean mailStudent, boolean msgStudent, boolean mailParent, boolean fillSchedule,
			boolean setExam, boolean updateResults, boolean authoriseStudent, boolean authoriseTeacher,
			boolean msgTeacher, boolean fillAttendance, boolean msgParent, boolean mailTeacher, Set<Teacher> teachers) {
		this.mailStudent = mailStudent;
		this.msgStudent = msgStudent;
		this.mailParent = mailParent;
		this.fillSchedule = fillSchedule;
		this.setExam = setExam;
		this.updateResults = updateResults;
		this.authoriseStudent = authoriseStudent;
		this.authoriseTeacher = authoriseTeacher;
		this.msgTeacher = msgTeacher;
		this.fillAttendance = fillAttendance;
		this.msgParent = msgParent;
		this.mailTeacher = mailTeacher;
		this.teachers = teachers;
	}

	
	public Permissions(Integer id, boolean mailStudent, boolean msgStudent, boolean mailParent, boolean fillSchedule,
			boolean setExam, boolean updateResults, boolean authoriseStudent, boolean authoriseTeacher,
			boolean msgTeacher, boolean fillAttendance, boolean msgParent, boolean mailTeacher) {
		super();
		this.id = id;
		this.mailStudent = mailStudent;
		this.msgStudent = msgStudent;
		this.mailParent = mailParent;
		this.fillSchedule = fillSchedule;
		this.setExam = setExam;
		this.updateResults = updateResults;
		this.authoriseStudent = authoriseStudent;
		this.authoriseTeacher = authoriseTeacher;
		this.msgTeacher = msgTeacher;
		this.fillAttendance = fillAttendance;
		this.msgParent = msgParent;
		this.mailTeacher = mailTeacher;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "mail_student", nullable = false)
	public boolean isMailStudent() {
		return this.mailStudent;
	}

	public void setMailStudent(boolean mailStudent) {
		this.mailStudent = mailStudent;
	}

	@Column(name = "msg_student", nullable = false)
	public boolean isMsgStudent() {
		return this.msgStudent;
	}

	public void setMsgStudent(boolean msgStudent) {
		this.msgStudent = msgStudent;
	}

	@Column(name = "mail_parent", nullable = false)
	public boolean isMailParent() {
		return this.mailParent;
	}

	public void setMailParent(boolean mailParent) {
		this.mailParent = mailParent;
	}

	@Column(name = "fill_schedule", nullable = false)
	public boolean isFillSchedule() {
		return this.fillSchedule;
	}

	public void setFillSchedule(boolean fillSchedule) {
		this.fillSchedule = fillSchedule;
	}

	@Column(name = "set_exam", nullable = false)
	public boolean isSetExam() {
		return this.setExam;
	}

	public void setSetExam(boolean setExam) {
		this.setExam = setExam;
	}

	@Column(name = "update_results", nullable = false)
	public boolean isUpdateResults() {
		return this.updateResults;
	}

	public void setUpdateResults(boolean updateResults) {
		this.updateResults = updateResults;
	}

	@Column(name = "authorise_student", nullable = false)
	public boolean isAuthoriseStudent() {
		return this.authoriseStudent;
	}

	public void setAuthoriseStudent(boolean authoriseStudent) {
		this.authoriseStudent = authoriseStudent;
	}

	@Column(name = "authorise_teacher", nullable = false)
	public boolean isAuthoriseTeacher() {
		return this.authoriseTeacher;
	}

	public void setAuthoriseTeacher(boolean authoriseTeacher) {
		this.authoriseTeacher = authoriseTeacher;
	}

	@Column(name = "msg_teacher", nullable = false)
	public boolean isMsgTeacher() {
		return this.msgTeacher;
	}

	public void setMsgTeacher(boolean msgTeacher) {
		this.msgTeacher = msgTeacher;
	}

	@Column(name = "fill_attendance", nullable = false)
	public boolean isFillAttendance() {
		return this.fillAttendance;
	}

	public void setFillAttendance(boolean fillAttendance) {
		this.fillAttendance = fillAttendance;
	}

	@Column(name = "msg_parent", nullable = false)
	public boolean isMsgParent() {
		return this.msgParent;
	}

	public void setMsgParent(boolean msgParent) {
		this.msgParent = msgParent;
	}

	@Column(name = "mail_teacher", nullable = false)
	public boolean isMailTeacher() {
		return this.mailTeacher;
	}

	public void setMailTeacher(boolean mailTeacher) {
		this.mailTeacher = mailTeacher;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permissions")
	public Set<Teacher> getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Set<Teacher> teachers) {
		this.teachers = teachers;
	}

}
