package com.app.pojo;
// Generated 21 Dec, 2017 11:23:34 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "schedule", catalog = "tutesmessanger", uniqueConstraints = @UniqueConstraint(columnNames = "division"))
public class Schedule implements java.io.Serializable {

	private Integer id;
	private transient Division division;
	private String string;

	public Schedule() {
	}

	public Schedule(Division division, String string) {
		this.division = division;
		this.string = string;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "division", unique = true)
	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	@Column(name = "string", length = 1000)
	public String getString() {
		return this.string;
	}

	public void setString(String string) {
		this.string = string;
	}

}
