package com.app.pojo;
// Generated 30 Jun, 2018 1:21:16 PM by Hibernate Tools 5.3.0.Beta2

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Smstemplate generated by hbm2java
 */

@Entity
@Table(name = "SMSTemplate", catalog = "tutesmessanger")
public class Smstemplate implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private String text;
	private String intendedFor;

	public Smstemplate() {
	}

	public Smstemplate(int id, String name, String intendedFor) {
		this.id = id;
		this.name = name;
		this.intendedFor = intendedFor;
	}

	public Smstemplate(int id, String name, String description, String text, String intendedFor) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.text = text;
		this.intendedFor = intendedFor;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@Column(name = "text", nullable = false, length = 200)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "intendedFor", nullable = false, length = 45)
	public String getIntendedFor() {
		return this.intendedFor;
	}

	public void setIntendedFor(String intendedFor) {
		this.intendedFor = intendedFor;
	}

}
