package com.app.pojo;
// Generated 10 Jan, 2018 5:07:20 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SubjectDivComposit generated by hbm2java
 */
@Entity
@Table(name = "subject_div_composit", catalog = "tutesmessanger", uniqueConstraints = @UniqueConstraint(columnNames = {
		"Div_id", "subject_id" }))
public class SubjectDivComposit implements java.io.Serializable {

	private Integer id;
	private transient Division division;
	private transient Subject subject;
	private transient Set<ExamSubjectStudentCompositTable> examSubjectStudentCompositTables = new HashSet<ExamSubjectStudentCompositTable>(
			0);

	public SubjectDivComposit() {
	}

	public SubjectDivComposit(Division division, Subject subject) {
		this.division = division;
		this.subject = subject;
	}

	public SubjectDivComposit(Division division, Subject subject,
			Set<ExamSubjectStudentCompositTable> examSubjectStudentCompositTables) {
		this.division = division;
		this.subject = subject;
		this.examSubjectStudentCompositTables = examSubjectStudentCompositTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Div_id", nullable = false)
	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subjectDivComposit")
	public Set<ExamSubjectStudentCompositTable> getExamSubjectStudentCompositTables() {
		return this.examSubjectStudentCompositTables;
	}

	public void setExamSubjectStudentCompositTables(
			Set<ExamSubjectStudentCompositTable> examSubjectStudentCompositTables) {
		this.examSubjectStudentCompositTables = examSubjectStudentCompositTables;
	}

}
