package com.app.pojo;
// Generated 21 Dec, 2017 11:23:34 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject", catalog = "tutesmessanger")
public class Subject implements java.io.Serializable {

	private Integer id;
	private String name;
	private String discription;
	private transient Set<ExamSubjectStudentCompositTable> examSubjectStudentCompositTables = new HashSet<ExamSubjectStudentCompositTable>(
			0);
	private transient Set<SubjectDivComposit> subjectDivComposits = new HashSet<SubjectDivComposit>(0);

	public Subject() {
	}

	public Subject(String name, String discription,
			Set<ExamSubjectStudentCompositTable> examSubjectStudentCompositTables,
			Set<SubjectDivComposit> subjectDivComposits) {
		this.name = name;
		this.discription = discription;
		this.examSubjectStudentCompositTables = examSubjectStudentCompositTables;
		this.subjectDivComposits = subjectDivComposits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "discription", length = 500)
	public String getDiscription() {
		return this.discription;
	}

	public void setDiscription(String discription) {
		this.discription = discription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set<ExamSubjectStudentCompositTable> getExamSubjectStudentCompositTables() {
		return this.examSubjectStudentCompositTables;
	}

	public void setExamSubjectStudentCompositTables(
			Set<ExamSubjectStudentCompositTable> examSubjectStudentCompositTables) {
		this.examSubjectStudentCompositTables = examSubjectStudentCompositTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set<SubjectDivComposit> getSubjectDivComposits() {
		return this.subjectDivComposits;
	}

	public void setSubjectDivComposits(Set<SubjectDivComposit> subjectDivComposits) {
		this.subjectDivComposits = subjectDivComposits;
	}

}
